version: "3.1"

services:
  web:
    build: .
    restart: always
    ports:
      - 80:3000
    environment:
      APP_PORT: 3000
      MONGO_URL: mongodb://root:example@mongo:27017/MyDb?authSource=admin
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodbdata:
  mongodbconfig:
